import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();
const chain = "arc_observed_5042";
const all = await p.token.count({ where: { chain } });
const filtered = await p.token.count({ where: { chain, AND: [{ NOT: { name: { startsWith: "qa_" } } }, { NOT: { symbol: { startsWith: "qa_" } } }] } });
const nullName = await p.token.count({ where: { chain, name: null } });
const nullSym = await p.token.count({ where: { chain, symbol: null } });
const nullEither = await p.token.count({ where: { chain, OR: [{ name: null }, { symbol: null }] } });
const realQa = await p.$queryRawUnsafe(`SELECT COUNT(*) c FROM Token WHERE chain='${chain}' AND (name LIKE 'qa\_%' ESCAPE '\' OR symbol LIKE 'qa\_%' ESCAPE '\')`);
const wildQa = await p.$queryRawUnsafe(`SELECT COUNT(*) c FROM Token WHERE chain='${chain}' AND ((name LIKE 'qa_%' AND name NOT LIKE 'qa\_%' ESCAPE '\') OR (symbol LIKE 'qa_%' AND symbol NOT LIKE 'qa\_%' ESCAPE '\'))`);
console.log({ all, filtered, nullName, nullSym, nullEither, realQa, wildQa });
const sample = await p.$queryRawUnsafe(`SELECT address,name,symbol FROM Token WHERE chain='${chain}' AND (name LIKE 'qa_%' AND name NOT LIKE 'qa\_%' ESCAPE '\') LIMIT 5`);
console.log(sample);
await p.$disconnect();
